name: Update Motivational Quote

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Fetch a random quote
        run: |
          QUOTE=$(curl -s https://api.quotable.io/random | jq -r '.content + " - " + .author')
          echo "QUOTE=$QUOTE" >> $GITHUB_ENV

      - name: Update README
        run: |
          sed -i "s|> <!--QUOTE-->|> $QUOTE|" README.md

      - name: Commit and push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://${GH_PAT}@github.com/SangramBehera2001/SangramBehera2001.git
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Updated motivational quote" && git push origin main)
